apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gcajuzdy8-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gcajuzdy8-dotnet-basic-gitops